### PR TITLE
Prod beta

### PR DESCRIPTION
**Pull request by indraraj**
For able to load the cos-ui in app-services-ui dev mode with running cos-ui locally

### CODE REVIEW

**Comment by riccardo-forina** [comment]
You should not open PRs against this manually, updates will automatically pushed by the CI/CD pipeline with changes coming from cos-ui

**Comment by indraraj** [comment]
> You should not open PRs against this manually, updates will automatically pushed by the CI/CD pipeline with changes coming from cos-ui

I believe the CI/CD pipeline for the prod(branches) is not set up and this was more to get some UI for cos without running it locally(for the time being).

**Comment by riccardo-forina** [comment]
There is qaprod set up to test the UI without running it locally. Doesn't that work?

**Comment by indraraj** [comment]
> There is qaprod set up to test the UI without running it locally. Doesn't that work?

As mentioned in the original comment this is for cos-ui to load in app-services-ui "**dev mode**" without running cos-ui locally. which I guess points to _prod.foo.redhat.com:1337_

**Comment by riccardo-forina** [comment]
That url is local only, you need to add it to your hosts file.

**Comment by indraraj** [comment]
thanks :)  I would connect after the holidays for this.

**Comment by indraraj** [comment]
closing this, as discussed will avoid manual deployment for pipeline

**Pull request closed without merging**
